---
  - hosts: elk
    become: True
    tasks:

    - name: set vm.max_map_count to 262144 in sysctl
      sysctl: name={{ item.key }} value={{ item.value }}
      with_items:
        - { key: "vm.max_map_count", value: "262144" }

    - name: Install docker.io (state=present is option)
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install python3 (state=present is option)
      apt:
        name: python3-pip
        state: present

    - name: Install docker python package
      pip:
        name: docker
        state: present

    - name: download and launch a docker elk container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        # Please list the ports that ELK runs on
        published_ports:
          -  5601:5601
          -  9200:9200
          -  5044:5044

    - name: Make sure docker service is started
      systemd:
        enabled: yes
        name: docker