---
  - name: Installing and Launch metricbeat
    hosts: webservers
    become: yes
    tasks:

    - name: Download and install metricbeat
      apt:
        deb: "https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb"
        state: present

      # Use copy module
    - name: Drop in metricbeat.yml
      copy:
        src: /etc/ansible/files/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

      # Use command module
    - name: Enable and Configure Docker Module
      command: metricbeat modules enable docker

      # Use command module
    - name: Setup metricbeat
      command: metricbeat setup

      # Use systemd module
    - name: Enable service metricbeat on boot
      systemd:
        name: metricbeat
        enabled: yes
        state: started